apiVersion: v1
kind: Service
metadata:
  labels:
    app: bugzilla
  name: bugzilla
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: bugzilla
