apiVersion: v1
kind: Service
metadata:
  name: insecure
  namespace: bugzilla
  annotations:
    external-dns.alpha.kubernetes.io/hostname: insecure.bugzilla.ninja
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: bugzilla

